### ISSUE TITLE
Add support of operation 'updateOne'

### ISSUE THREAD

**Issue by schernolyas** [epam/hibernate-ogm#4]
https://hibernate.atlassian.net/browse/OGM-1315

**Comment by Ilonich** [comment]
Pull request:
https://github.com/epam/hibernate-ogm/pull/5

**Comment by Ilonich** [comment]
Request https://github.com/epam/hibernate-ogm/pull/5

**Comment by Ilonich** [comment]
Merged:
[comment](https://github.com/epam/hibernate-ogm/pull/5#issuecomment-336034202)
